from setuptools import setup, find_packages

setup(
    name='kgraphgen',
    version='0.0.2',
    author='Marc Hadfield',
    author_email='marc@vital.ai',
    description='KGraph Generate',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/vital-ai/kgraphgen',
    packages=find_packages(exclude=["test", "test_data", "test_data_internal", "test_output", "test_docbin"]),
    license='Apache License 2.0',
    install_requires=[
            'requests>=2.31.0',
            'vital-ai-vitalsigns>=0.1.27',
            'vital-ai-domain>=0.1.4',
            'six',
            'pyyaml',
            'vital-ai-haley-kg>=0.1.22',
            'kgraphmemory>=0.0.7',
            'kgraphservice>=0.0.6',
            'vital-agent-kg-utils>=0.1.0',
            'rdflib==7.0.0',
            'SPARQLWrapper==2.0.0',
            'networkx',
            'matplotlib',
            'langchain>=0.1.20',
            'openai>=1.28.0',
            'langchain-openai>=0.1.6',
            # 'openapi-schema-pydantic==1.2.4',
            'pydantic>=1.10.12',
            'scikit-learn>=1.4.2',
            'sentence_transformers==2.7.0',
            'hdbscan==0.8.33',
            'pandas==2.2.2',
            'numpy==1.26.4',
            'beautifulsoup4==4.12.3',
            'wikipedia-api==0.6.0',
            'spacy==3.7.4',
            'nltk',
            'sentence_transformers'
    ],
    classifiers=[
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.10',
)
